services:
  postgres:
    image: postgres:latest
    container_name: rentplace_postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  
  backend:
    container_name: rentplace_main_service
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      UPLOAD_PATH: /uploads/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/$DB_NAME
      SPRING_DATASOURCE_USERNAME: $DB_USER
      SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SERVER_PORT: 8080
volumes:
  pgdata:      